### ISSUE TITLE
你好，请问下数据处理文件data_process.py加载的预训练语言模型chinese_roberta_csc_pinyin是预训练了ReaLiSe中的拼音bert得到的吗？

### ISSUE THREAD

**Issue by YaoYao5** [liangzh63/DORM-CSC#1]

**Comment by liangzh63** [comment]
你好。不是的。

--------------原始邮件--------------
发件人："YaoYao5 ***@***.***&gt;;
发送时间：2023年11月3日(星期五) 下午4:48
收件人："liangzh63/DORM-CSC" ***@***.***&gt;;
抄送："Subscribed ***@***.***&gt;;
主题：[liangzh63/DORM-CSC] 你好，请问下数据处理文件data_process.py加载的预训练语言模型chinese_roberta_csc_pinyin是预训练了ReaLiSe中的拼音bert得到的吗？ (Issue #1)
-----------------------------------

**Comment by YaoYao5** [comment]
谢谢作者，那请问下可以公开下处理好之后的数据吗？如果不方便公开模型chinese_roberta_csc_pinyin的话。

**Comment by liangzh63** [comment]
可以尝试按照论文方法处理就好，只需在词表加上对应的拼音即可

--------------原始邮件--------------
发件人："YaoYao5 ***@***.***&gt;;
发送时间：2023年11月3日(星期五) 下午5:03
收件人："liangzh63/DORM-CSC" ***@***.***&gt;;
抄送："梁子宏 ***@***.***&gt;;"Comment ***@***.***&gt;;
主题：Re: [liangzh63/DORM-CSC] 你好，请问下数据处理文件data_process.py加载的预训练语言模型chinese_roberta_csc_pinyin是预训练了ReaLiSe中的拼音bert得到的吗？ (Issue #1)
-----------------------------------

 

 
谢谢作者，那请问下可以公开下处理好之后的数据吗？如果不方便公开模型chinese_roberta_csc_pinyin的话。

**Comment by YaoYao5** [comment]
好的，谢谢作者
